### PR TITLE
fix(eslint-plugin-template): [attributes-order] Handle explicit ng-template usage

### LINKED ISSUE #1456: [@angular-eslint/template/attributes-order] Cannot read properties of undefined (reading 'sourceSpan')
**Description and reproduction of the issue**

```JSON
{
  "rules": {
    "'@angular-eslint/template/attributes-order": ["error"]
  }
}
```

This code (combination of `ng-template` and `mat-icon`) leads to the following error.

```HTML
<ng-template>
  <mat-icon>assignment</mat-icon>
</ng-template>
```

```sh
[error] TypeError: Cannot read properties of undefined (reading 'sourceSpan')
Occurred while linting /Users/.../src/app/.../pages/detail/detail.component.html:10
Rule: "@angular-eslint/template/attributes-order"
    at extractTemplateAttrs (/Users/.../node_modules/@angular-eslint/eslint-plugin-template/dist/rules/attributes-order.js:193:45)
    at Element$1 (/Users/.../node_modules/@angular-eslint/eslint-plugin-template/dist/rules/attributes-order.js:81:24)
    at ruleErrorHandler (/Users/.../node_modules/eslint/lib/linter/linter.js:1050:28)
    at /Users/.../node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/.../node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/.../node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/Users/.../node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/Users/.../node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/Users/.../node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
```

Unfortunately, I haven't yet got time to prepare a stackblitz but the problem is here https://github.com/angular-eslint/angular-eslint/blob/main/packages/eslint-plugin-template/src/rules/attributes-order.ts#L303. I checked the `attrs` variable at the error, and it is empty (seems correct to me, `ng-template` doesn't have any attributes). Therefore `attrs[attrs.length - 1]` leads to undefined.

If I add an attribute to the `ng-template`:

```html
<ng-template mat-tab-label>
  <mat-icon>assignment</mat-icon>
</ng-template>
```

The error still occurs, `attrs` is empty. However, the attribute `mat-tab-label` appears in the `node.parent.attributes` but not in the `node.parent.templateAttrs`.

**Versions**

| package                                   | version |
| ----------------------------------        | ------- |
| `@angular-eslint/eslint-plugin-template`  | `16.1.0` |
| `@angular-eslint/template-parser`         | `16.1.0` |
| `@typescript-eslint/parser`               | `6.0.0` |
| `ESLint`                                  | `8.44.0` |
| `node`                                    | `18.10.0` |

```sh

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 16.1.4
Node: 18.10.0
Package Manager: npm 8.15.0
OS: darwin arm64

Angular: 16.1.4
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.4
@angular-devkit/build-angular   16.1.4
@angular-devkit/core            16.1.4
@angular-devkit/schematics      16.1.4
@angular/fire                   7.6.1
@schematics/angular             16.1.4
ng-packagr                      16.1.0
rxjs                            7.8.1
typescript                      5.0.4
```

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

### PR DESCRIPTION
**Pull request by pmccloghrylaing**
Fixes #1456

### CODE REVIEW

File: packages/eslint-plugin-template/src/rules/attributes-order.ts [hunk 1]
```diff
@@ -283,10 +290,35 @@ function toTemplateReferenceVariableOrderType(reference: TmplAstReference) {
...
+
 function extractTemplateAttrs(
-  node: ExtendedTmplAstElement,
+  node: ExtendedTmplAstElement | TmplAstTemplate,
 ): (ExtendedTmplAstBoundAttribute | ExtendedTmplAstTextAttribute)[] {
-  if (!isTmplAstTemplate(node.parent)) {
+  if (isTmplAstTemplate(node)) {
+    return node.templateAttrs.map(toStructuralDirectiveOrderType).concat(
+      node.variables.map((x) => {
+        console.log(
```
Comment (sandikbarr) [inline packages/eslint-plugin-template/src/rules/attributes-order.ts:305]: please remove console.log ;)

File: packages/eslint-plugin-template/tests/rules/attributes-order/cases.ts [hunk 2]
```diff
@@ -299,4 +303,21 @@ export const invalid = [
...
+    options: [{ alphabetical: true }],
+    data: {
+      expected: '`#Template`, `let-value`',
+      actual: '`let-value`, `#Template`',
+    },
+    annotatedOutput: `
+      <ng-template #Template let-value></ng-template>
+                   
+    `,
+  }),
```
Comment (sandikbarr) [inline packages/eslint-plugin-template/tests/rules/attributes-order/cases.ts:322]: 👍 I also validated the fixer using this test case with multiple variables and assignment:
```suggestion
  }),
  convertAnnotatedSourceToFailureCase({
    messageId,
    description: 'should work with ng-template with multiple variable assignments',
    annotatedSource: `
      <ng-template let-value="something" let-anotherValue="else" #Template></ng-template>
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    `,
    options: [{ alphabetical: true }],
    data: {
      expected: '`#Template`, `let-anotherValue`, `let-value`',
      actual: '`let-value`, `let-anotherValue`, `#Template`',
    },
    annotatedOutput: `
      <ng-template #Template let-anotherValue="else" let-value="something"></ng-template>
                   
    `,
  }),
```

**Review by sandikbarr — APPROVED** [review]

**Review by abaran30 — APPROVED** [review]

**Comment by robertIsaac** [comment]
when do you plan to release this?
