### PR TITLE
fix(template-parser): generate correct index.d.ts when building

### LINKED ISSUE #479: published `types` is incorrect
**Description and reproduction of the issue**

https://unpkg.com/browse/@angular-eslint/template-parser@12.0.0/dist/index.d.ts

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint       `        | `X.Y.Z` |
| `TypeScript`                       | `X.Y.Z` |
| `ESLint`                           | `X.Y.Z` |
| `node`                             | `X.Y.Z` |

```sh
# Please run `npx ng version` in your project and paste the full output here:


```

- [ ] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

### PR DESCRIPTION
**Pull request by JamesHenry**
Fixes #479

### CODE REVIEW

File: packages/template-parser/src/index.ts [hunk 1]
```diff
@@ -246,7 +246,7 @@ function parseForESLint(code: string, options: { filePath: string }) {
   };
 }
 
-module.exports = {
+export default {
```
Comment (JounQin) [inline packages/template-parser/src/index.ts:249]: @JamesHenry 

Why not use `export { parseForESLint, parse }`?

So that it will also work with cjs + `@ts-check`?

image

Comment (JamesHenry) [reply packages/template-parser/src/index.ts:249]: It's written in the comment on this PR:

```
/**
 * This usage seems a little wonky, but don't want to run any risk of breaking changes
 * to the compiled output of the template-parser node module, so leaving until v13.
 */
```

Comment (JamesHenry) [reply packages/template-parser/src/index.ts:249]: This is not blocking anything AFAICT, you can achieve everything you need to via the default export and it will work with ts-check

Comment (JounQin) [reply packages/template-parser/src/index.ts:249]: It doesn't, `require('@angular-eslint/template-parser')`

```js
// index.js
const _ = require('@angular-eslint/template-parser')

console.log(_.default)
console.log(_.parseForESLint)
```

```log
$ tsc -p jsconfig.json
index.js:11:15 - error TS2339: Property 'parseForESLint' does not exist on type 'typeof import("/workspace/angular-eslint-template-parser/node_modules/@angular-eslint/template-parser/dist/index")'.

11 console.log(_.parseForESLint)
```

```log
// run `node index.js`
undefined
[Function: u]
```

Comment (JounQin) [reply packages/template-parser/src/index.ts:249]: > It's written in the comment on this PR:

The current solution is actually a breaking change for typings.

Why `export { parseForESLint }` would break too? I think it will be just fine.

Comment (JounQin) [reply packages/template-parser/src/index.ts:249]: @JamesHenry Hi, any possible to fix?
