### PR TITLE
fix(eslint-plugin-template): [eqeqeq] Calculate offset to find true absolute source span

### LINKED ISSUE #1666: [eqeqeq] Incorrectly updates the template when run with '--fix' option
**Description and reproduction of the issue**

Please see isolated reproduction repo at [eslint-autofix-issue](https://github.com/phalgunv/eslint-autofix-issue). Steps to reproduce

1. git clone https://github.com/phalgunv/eslint-autofix-issue
2. cd eslint-autofix-issue; npm install;
3. npm run ng lint -- --fix

app.component.html will get updated incorrectly after step 3. 
Please note, the code in this repository is a strip-down version of code from a enterprise project where the issue was originally found.

```JSON
{
  "rules": {
    "@angular-eslint/template/eqeqeq": "error"
  }
}
```

```HTML
<h1>Minimal example to demo issue with eslint --fix</h1>
<ng-container>
	<ng-container>
		<ng-container>
			<ng-container>
				<ng-container>
					<ng-container>
						<ng-container>
							<app-test
								[labelStyle]="
									formGroup.controls[field.options.stateKey].value == '' &&
									formGroup.controls[field.options.stateKey].dirty
										? invalidLabelStyle
										: labelStyle
								"
							>
							</app-test>
						</ng-container>
					</ng-container>
				</ng-container>
			</ng-container>
		</ng-container>
	</ng-container>
</ng-container>
```

**Versions**

| package                                   | version |
| ----------------------------------        | ------- |
| `@angular-eslint/eslint-plugin-template`  | `15.2.1` |
| `@angular-eslint/template-parser`         | `15.2.1` |
| `@typescript-eslint/parser`               | `5.48.2` |
| `ESLint`                                  | `^8.33.0` |
| `node`                                    | `v16.20.0` |

```sh
# Please run `npx ng version` in your project and paste the full output here:
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 15.2.10
Node: 16.20.0
Package Manager: npm 8.19.4
OS: linux x64

Angular: 15.2.10
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.10
@angular-devkit/build-angular   15.2.10
@angular-devkit/core            15.2.10
@angular-devkit/schematics      15.2.10
@schematics/angular             15.2.10
rxjs                            7.8.1
typescript                      4.9.5

```

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

### PR DESCRIPTION
**Pull request by estevezluis**
Fixes #1666 

Problem:
In angular's parser, leading whitespace or newline is ignored when calculating AbsoluteSourceSpan. [^1][^2]

Solution:
This PR finds the true AbsoluteSourceSpan by calculating the leading trivia characters offset.

Assistance requested:
Not sure how to add a leading newline (e.g. code snippet in #1666) in `annotatedSource` without causing issues in `annotatedOutput`.

Reference

[^1]: https://github.com/angular/angular/blob/main/packages/compiler/src/ml_parser/lexer.ts#L87

[^2]: https://hackmd.io/@X3ECPVy-RCuVfba-pnvIpw/BkDUxaW84/%2FMA1oxh6jRXqSmZBcLfYdyw?type=book)%5C#Parser

### CODE REVIEW

File: packages/eslint-plugin-template/src/rules/eqeqeq.ts [hunk 1]
```diff
@@ -74,14 +75,22 @@ export default createESLintRule<Options, MessageIds>({
...
                 suggest: [
                   {
                     messageId: 'suggestStrictEquality',
                     fix: (fixer) =>
-                      getFix({ node, left, right, start, end, fixer }),
+                      getFix({
+                        node,
+                        left,
+                        right,
+                        start,
```
Comment (estevezluis) [inline packages/eslint-plugin-template/src/rules/eqeqeq.ts:89]: Not sure how to test the code format change 😄

**Comment by JamesHenry** [comment]
Thanks a lot for this @estevezluis!
