### PR TITLE
fix(eslint-plugin-template): [attributes-order] fixes for structural …

### LINKED ISSUE #1500: [attributes-order] auto-fix results in invalid HTML
**Description and reproduction of the issue**

```JSON
{
  "rules": {
    "@angular-eslint/template/attributes-order": "error"
  }
}
```

```HTML
// Input
<td mat-cell *matCellDef="let element"></td>
// Output
<td *matCellDef= mat-cell"let element"></td>
```

**Versions**

| package                                   | version |
| ----------------------------------        | ------- |
| `@angular-eslint/eslint-plugin-template`  | `16.1.1` |
| `@angular-eslint/template-parser`         | `16.1.1` |
| `@typescript-eslint/parser`               | `16.1.1` |
| `ESLint`                                  | `8.47.0` |
| `node`                                    | `16.19.0` |

```sh
# Please run `npx ng version` in your project and paste the full output here:

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 16.2.0
Node: 16.19.0
Package Manager: pnpm 8.7.0
OS: linux x64

Angular: 16.2.1
... animations, cdk, cdk-experimental, common, compiler
... compiler-cli, core, forms, language-service, material
... material-moment-adapter, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.0
@angular-devkit/build-angular   16.2.0
@angular-devkit/core            16.2.0
@angular-devkit/schematics      16.2.0
@angular/cli                    16.2.0
@schematics/angular             16.2.0
ng-packagr                      16.2.0
rxjs                            7.8.1
typescript                      5.1.6
webpack                         5.88.2
zone.js                         0.13.1
    


```

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

### PR DESCRIPTION
**Pull request by pmccloghrylaing**
…directives and i18n ordering

Fixes #1500, #1519

### CODE REVIEW

File: packages/eslint-plugin-template/src/rules/attributes-order.ts [hunk 1]
```diff
@@ -328,23 +334,28 @@ function extractTemplateAttrs(
...
+    const apos = keyEnd.getContext(0, 0)?.after;
+    if (apos === "'" || apos === '"') {
+      do {
+        keyEnd = keyEnd.moveBy(1);
+      } while (keyEnd.getContext(0, 0)?.after !== apos);
+    } else {
+      while (!/[\s>]/.test(keyEnd.getContext(0, 0)?.after ?? '')) {
+        keyEnd = keyEnd.moveBy(1);
+      }
     }
```
Comment (pmccloghrylaing) [inline packages/eslint-plugin-template/src/rules/attributes-order.ts:349]: Instead of trying to merge multiple spans it works out the value span separately. This deals with contained template variables and extra whitespace within the value.

**Comment by abaran30** [comment]
FYI @skrtheboss

File: packages/eslint-plugin-template/tests/rules/attributes-order/cases.ts [hunk 2]
```diff
@@ -338,4 +339,64 @@ export const invalid = [
...
+          
+        let element
+        
+      " mat-cell></td>
+      
+    `,
+  }),
+  convertAnnotatedSourceToFailureCase({
+    messageId,
+    description: 'should work with structural directive with as',
```
Comment (abaran30) [inline packages/eslint-plugin-template/tests/rules/attributes-order/cases.ts:387]: Suggesting this change because structural directives with `as` have been working before this PR. Only when a trailing whitespace exists does the auto-fixer break.
```suggestion
    description: 'should work with structural directive with as and trailing whitespace',
```

**Review by abaran30 — APPROVED** [review]

**Comment by JamesHenry** [comment]
Thank you both!
