### PR TITLE
fix(eslint-plugin): [component-selector] enhance check for prefix and…

### LINKED ISSUE #318: kebab-case option warns of single words in component-selector
While creating the docs for the rule [component-selector](https://github.com/angular-eslint/angular-eslint/blob/master/packages/eslint-plugin/src/rules/component-selector.ts), I found an error message different from what I expected

#### Expected message

`The selector should be prefixed by one of the prefixes: 'app,toh' (https://angular.io/guide/styleguide#style-02-07) eslint@angular-eslint/component-selector`

#### Received message

`The selector should be kebab-case (https://angular.io/guide/styleguide#style-05-02) eslint@angular-eslint/component-selector`

#### Configuration
```json
"rules": {
    "@angular-eslint/component-selector": [
        "warn",
        {
            "type": "element",
             "style": "kebab-case",
             "prefix": ["app", "toh"]
        }
    ]
}
```

#### Code
```ts
@Component({
  selector: 'root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {}
```

Digging through the code, I found this to be a [deliberate decision](https://github.com/angular-eslint/angular-eslint/blob/c44cd5d043a3d203efd1faaed4cbfee2c9ac2e9d/packages/eslint-plugin/tests/rules/component-selector.test.ts#L285-L296). Why is it? I mean, a single word like `app` is a valid kebab-cased word (from what I known).

### PR DESCRIPTION
**Pull request by abaran30**
...kebab-case

Resolves #318 

This pull request contains the following changes to accommodate the discussion had in #318:
- Add new error message in rule `component-selector` for invalid prefix ***and*** case
- Add test cases to verify the examples posted in the issue

### CODE REVIEW

**Comment by abaran30** [comment]
TODO: this change allows for selectors like `sgggggggg-foo-bar`; not ideal... Thank you @sandikbarr for catching this!

File: packages/eslint-plugin/src/rules/pipe-prefix.ts [hunk 1]
```diff
@@ -88,7 +88,7 @@ export default createESLintRule<Options, MessageIds>({
           return;
         }
 
-        if (!prefixValidator.apply(this, [nameValue])) {
+        if (!prefixValidator.apply(this, [nameValue]) || !styleValidator) {
```
Comment (sandikbarr) [inline packages/eslint-plugin/src/rules/pipe-prefix.ts:91]: Does this styleValidator need to be called as a function with the nameValue?

File: packages/eslint-plugin/tests/rules/component-selector/cases.ts [hunk 2]
```diff
@@ -302,9 +312,9 @@ export const invalid = [
         })
         class Test {}
       `,
-    messageId: messageIdStyleFailure,
+    messageId: messageIdStyleAndPrefixFailure,
```
Comment (abaran30) [inline packages/eslint-plugin/tests/rules/component-selector/cases.ts:315]: Note: the reported error for this invalid case has changed to the new error message. Although it's not incorrect, the former is more concise for this particular case. I think the only way to retain the original message is to move the style logic inside the prefix validator to its own validator (which I did attempt in a previous commit). However, this will result in a more complex conditional in the rule when determining which message to report.

LMK your thoughts!

Comment (sandikbarr) [reply packages/eslint-plugin/tests/rules/component-selector/cases.ts:315]: This seems acceptable to me as a non breaking change while addressing the original issue.

**Review by sandikbarr — APPROVED** [review]
thanks for digging into this!

**Comment by abaran30** [comment]
@JamesHenry ready for review. LMK what you think.

**Review by JamesHenry — APPROVED** [review]
Thank you @abaran30 (and @sandikbarr)! And sorry for the delay in reviewing
