### PR TITLE
fix(eslint-plugin-template): [i18n] remove unsafe fix

### LINKED ISSUE #400: [i18n] fix adds errors to templates
**Description and reproduction of the issue**

I have a section in my template that looks like this
```
<div [hidden]="compact">
      {{ totalAssets | ngrxPush }} <span class="hidden small:inline" i18n="@@assets.list.total">total</span> /
      <ng-container *ngrxLet="selectedAmount$; let selectedAmount">
        <button class="show-selected" [disabled]="selectedAmount === 0" (click)="openSelectionOverlay()">
          {{ selectedAmount }}
          <span class="hidden small:inline" i18n="@@assets.list.selected">selected</span>
        </button>
      </ng-container>
    </div>
```

ESLint fix adds an i18n to the surounding div which then results in `Cannot mark an element as translatable inside of a translatable section. Please remove the nested i18n marker.`

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint       `        | `4.20.0` |
| `TypeScript`                       | `4.1.5` |
| `ESLint`                           | `7.23.0` |
| `node`                             | `14.16.0` |

```sh
# Please run `npx ng version` in your project and paste the full output here:
Angular CLI: 11.2.6
Node: 14.16.0
OS: darwin x64

Angular: 11.2.8
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.4
@angular-devkit/build-angular   0.1102.6
@angular-devkit/core            11.2.4
@angular-devkit/schematics      11.2.6
@angular/cdk                    11.2.7
@angular/cli                    11.2.6
@angular/material               11.2.7
@schematics/angular             11.2.6
@schematics/update              0.1102.6
rxjs                            6.6.7
typescript                      4.1.5
webpack                         4.46.0

```

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

### PR DESCRIPTION
**Pull request by rafaelss95**
Fixes #400.

### CODE REVIEW

File: packages/eslint-plugin-template/src/rules/i18n.ts [hunk 1]
```diff
@@ -248,15 +248,9 @@ export default createESLintRule<Options, MessageIds>({
                 )),
           )
         ) {
-          // If at least one child is a text node then we probably need i18n
```
Comment (rafaelss95) [inline packages/eslint-plugin-template/src/rules/i18n.ts:251]: As the comment says: "[...] we **_probably_** need i18n". I decided to remove this as we can't guarantee that this fix is safe.

**Comment by JamesHenry** [comment]
In the future we could possibly leverage "suggestions" for these cases: https://eslint.org/docs/developer-guide/working-with-rules#providing-suggestions

I haven't used them before myself but they are a possibility
